# This is a basic workflow to help you get started with Actions

name: 'Debugger'

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: csexton/debugger-action@master
