# This is a basic workflow to help you get started with Actions

name: 'Debugger'

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
runs:
  using: 'node12'
  main: 'action.js'
branding:
  icon: 'terminal'
  color: 'green'
